# Generated by Django 5.1 on 2024-09-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=225)),
                ('pbrand', models.CharField(max_length=225)),
                ('pprice', models.IntegerField(max_length=225)),
                ('psellprice', models.IntegerField(max_length=225)),
                ('pdiscount', models.IntegerField(max_length=225)),
                ('pimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
