# Generated by Django 5.1 on 2024-09-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img'),
        ),
    ]
