# Generated by Django 5.1 on 2024-10-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_product_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='freeread_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='main_image')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
