# Generated by Django 5.1 on 2024-10-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_freeread_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeread_db',
            name='des',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='freeread_db',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
