# Generated by Django 5.1 on 2024-12-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product_db_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='carasoul_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='', upload_to='carasoul')),
                ('img2', models.ImageField(default='', upload_to='carasoul')),
                ('img3', models.ImageField(default='', upload_to='carasoul')),
                ('img4', models.ImageField(default='', upload_to='carasoul')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
