# Generated by Django 5.1 on 2024-12-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_carasoul_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carasoul_db',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='carasoul_db',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='carasoul_db',
            name='img4',
        ),
    ]
