# Generated by Django 5.1 on 2024-08-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='checkbox',
            field=models.CharField(default=1, max_length=225),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
