# Generated by Django 5.1 on 2024-09-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customerlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customerlogin',
        ),
    ]
