# Generated by Django 5.1 on 2024-10-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=6)),
            ],
        ),
    ]
