# Generated by Django 5.1 on 2024-10-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customerread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customerread',
        ),
    ]
